configuration: Release

image: Visual Studio 2019

# restore NuGet packages before running MSBuild
#before_build:
#  - nuget restore

build:
  project: swiftly-services-exercise.csproj
  publish_core_console: true
