configuration: Release

image: Visual Studio 2019

# restore NuGet packages before running MSBuild
before_build:
  - nuget restore -PackagesDirectory packages swiftly-services-exercise.csproj

build:
  project: swiftly-services-exercise.csproj
  publish_core_console: true
