configuration: Release

image: Visual Studio 2019

# restore NuGet packages before running MSBuild
before_build:
  - nuget restore -PackagesDirectory packages swiftly-exercise.sln

build:
  project: swiftly-exercise.sln
  publish_core_console: true
